import { useState, useEffect } from "react";
import { T } from "../../tokens";
import { Btn, Spin } from "../../components/ui";

const ContractModal=({tx,scope,onClose})=>{
  const [ld,setLd]=useState(true);const [contract,setContract]=useState("");
  useEffect(()=>{
    (async()=>{
      try{
        const r=await fetch("https://api.anthropic.com/v1/messages",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({model:"claude-sonnet-4-20250514",max_tokens:1200,messages:[{role:"user",content:`Generate a professional tech services escrow agreement.\nProject: ${tx?.title||"Tech Services Project"}\nCategory: ${tx?.type||"Software Development"}\nValue: $${tx?.amount?.toLocaleString()||"TBD"} ${tx?.currency||"USD"}\nProvider: ${tx?.other||"[Provider]"}\nScope: ${scope?JSON.stringify(scope):"As agreed"}\n\nWrite a concise, professional escrow agreement covering: parties, project, deliverables, payment terms, milestone structure, revision policy, escrow terms, dispute resolution, governing law. No markdown — use numbered sections.`}]})});
        const d=await r.json();setContract(d.content?.map(i=>i.text||"").join("")||"");
      }catch{setContract(`TECH SERVICES ESCROW AGREEMENT\n\n1. PARTIES\nThis Agreement is between the Client and Service Provider, facilitated by Escrow Escrow Services ("Escrow Agent").\n\n2. PROJECT SCOPE\nThe Service Provider agrees to deliver "${tx?.title}" as described in the attached scope document within the agreed timeline.\n\n3. PAYMENT TERMS\nTotal project value: $${tx?.amount?.toLocaleString()||"TBD"} ${tx?.currency||"USD"}. Funds held in Escrow's regulated trust account until deliverables are accepted.\n\n4. MILESTONE PAYMENTS\nPayments released per milestone upon Client approval following AI audit confirmation.\n\n5. REVISION POLICY\nClient is entitled to two (2) revision rounds per milestone. Additional revisions quoted separately.\n\n6. DISPUTE RESOLUTION\nUnresolved disputes submitted to Escrow's Dispute Resolution Officer. Decision binding within 5 business days.\n\n7. ESCROW TERMS\nFunds held in segregated, regulated trust accounts. Released only on Client approval or binding dispute resolution.\n\n8. GOVERNING LAW\nThis Agreement is governed by applicable jurisdiction law.`);}
      setLd(false);
    })();
  },[]);
  return(
    <div style={{position:"fixed",inset:0,background:"rgba(0,0,0,.6)",zIndex:700,display:"flex",alignItems:"center",justifyContent:"center",padding:16,backdropFilter:"blur(4px)"}} onClick={e=>e.target===e.currentTarget&&onClose()}>
      <div style={{background:T.white,borderRadius:20,width:"100%",maxWidth:640,maxHeight:"90vh",overflow:"hidden",display:"flex",flexDirection:"column",boxShadow:"0 32px 80px rgba(0,0,0,.28)",animation:"fadeUp .3s ease"}}>
        <div style={{background:"linear-gradient(135deg,#3730a3,#4338ca)",padding:"22px 26px",color:T.white,display:"flex",justifyContent:"space-between",alignItems:"center",flexShrink:0}}>
          <div><div style={{fontWeight:800,fontSize:17,display:"flex",alignItems:"center",gap:8}}><span className="msym" style={{fontSize:20}}>description</span>AI Contract Generator</div><div style={{fontSize:12,opacity:.65,marginTop:3}}>{tx?.title||"Tech Services Escrow Contract"}</div></div>
          <button onClick={onClose} style={{background:"rgba(255,255,255,.12)",border:"none",color:T.white,borderRadius:"50%",width:30,height:30,cursor:"pointer",fontSize:16,display:"flex",alignItems:"center",justifyContent:"center"}}>×</button>
        </div>
        <div style={{flex:1,overflowY:"auto",padding:"26px"}}>
          {ld?(
            <div style={{textAlign:"center",padding:"48px 0"}}><span className="msym" style={{fontSize:42,color:T.primary,display:"block",marginBottom:14,animation:"pulse 1.5s ease infinite"}}>description</span><div style={{fontWeight:700,fontSize:16,color:T.primary,marginBottom:8}}>Generating contract…</div><p style={{fontSize:13,color:T.gray500}}>AI is drafting a legally-sound escrow agreement.</p></div>
          ):(
            <>
              <div style={{background:"#eef2ff",border:"1px solid #c7d2fe",borderRadius:10,padding:"13px 15px",fontSize:13,color:"#3730a3",lineHeight:1.65,marginBottom:20}}><span className="msym" style={{fontSize:16,verticalAlign:"middle",marginRight:6}}>check_circle</span>Contract generated by Escrow AI. Review before both parties sign.</div>
              <div style={{background:T.offWhite,borderRadius:12,padding:"20px 22px",fontSize:13,color:T.gray700,lineHeight:2,whiteSpace:"pre-wrap",fontFamily:"Georgia, serif"}}>{contract}</div>
            </>
          )}
        </div>
        {!ld&&(
          <div style={{padding:"16px 26px",borderTop:`1px solid ${T.gray100}`,display:"flex",gap:10,flexShrink:0}}>
            <Btn variant="outline" onClick={onClose} style={{flex:1}}>Close</Btn>
            <Btn variant="purple" style={{flex:1}}><span className="msym" style={{fontSize:17}}>download</span>Download PDF</Btn>
            <Btn variant="primary" onClick={onClose} style={{flex:1}}><span className="msym" style={{fontSize:17}}>check_circle</span>Accept Contract →</Btn>
          </div>
        )}
      </div>
    </div>
  );
};
export default ContractModal;
